// apps/mobile/src/screens/not-found.tsx
import { useNavigation } from '@react-navigation/native'
import { View } from 'react-native'

import { Button } from '@/components/ui/button'
import { Text } from '@/components/ui/text'

export default function NotFoundScreen() {
  const navigation = useNavigation()

  return (
    <View className='flex-1 bg-background'>
      <View className='container flex-1 items-center justify-center gap-6'>
        <Text variant='h1'>404 - Not Found</Text>

        <Button
          onPress={() =>
            navigation.navigate('tabs', { screen: 'index' }, { pop: true })
          }
        >
          <Text>Take me Home</Text>
        </Button>
      </View>
    </View>
  )
}

// apps/goldenglow/src/routes/not-found.vue
<template>
  <main
    class="container flex min-h-[calc(100dvh-4rem)] flex-col items-center justify-center gap-4"
  >
    <div class="flex items-center gap-4">
      <Typography variant="h2" class="mb-0">404</Typography>
      <div class="h-16 w-0.5 bg-secondary lg:h-20" />
      <Typography variant="h3" class="mb-0">Page Not Found</Typography>
    </div>

    <Button as="RouterLink" to="/"> Take me home </Button>
  </main>
</template>

<script setup lang="ts">
import { Button } from '@/components/ui/button'
import { Typography } from '@/components/ui/typography'
</script>
