// apps/web/app/not-found.tsx
'use client'

import Image from 'next/image'
import Link from 'next/link'

import { buttonVariants } from '@yukinu/ui/button'
import { Typography } from '@yukinu/ui/typography'

export default function DocsNotFoundError() {
  return (
    <main className='container flex min-h-[calc(100dvh-1.5rem)] flex-col items-center justify-center gap-8'>
      <Image
        src='/assets/images/yuki.webp'
        alt='Yuki Not Found'
        width={500}
        height={500}
        priority
      />

      <Typography variant='h2' className='text-center'>
        404 - Page Not Found
      </Typography>

      <Typography className='text-center text-muted-foreground'>
        Sorry, the page you are looking for does not exist.
      </Typography>

      <Link href='/' className={buttonVariants({ size: 'lg' })}>
        Take me home
      </Link>
    </main>
  )
}

// apps/goldenglow/src/routes/not-found.vue
<template>
  <main
    class="container flex min-h-[calc(100dvh-4rem)] flex-col items-center justify-center gap-4"
  >
    <div class="flex items-center gap-4">
      <Typography variant="h2" class="mb-0">404</Typography>
      <div class="h-16 w-0.5 bg-secondary lg:h-20" />
      <Typography variant="h3" class="mb-0">Page Not Found</Typography>
    </div>

    <Button as="RouterLink" to="/"> Take me home </Button>
  </main>
</template>

<script setup lang="ts">
import { Button } from '@/components/ui/button'
import { Typography } from '@/components/ui/typography'
</script>
