// apps/goldenglow/src/routes/_index.vue
<template>
  <main class="container py-4">
    <template v-if="isLoading">
      <p>Loading...</p>
    </template>

    <div
      v-else
      class="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4"
    >
      <RouterLink
        v-for="product in data.products"
        :key="product.id"
        :to="`/${product.id}`"
        class="flex flex-col gap-4 rounded-xl border bg-card pb-6 text-card-foreground shadow-sm"
      >
        <img :src="product.image" class="rounded-t-xl" />
        <div
          class="@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 px-4 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6"
        >
          <p class="leading-none font-semibold">{{ product.name }}</p>
          <p class="text-sm font-medium">${{ product.price }}</p>
          <p class="truncate text-sm text-muted-foreground">
            {{ product.description }}
          </p>
        </div>
      </RouterLink>
    </div>
  </main>
</template>

<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'

import { productOptions } from '@/api/product'
import { trpc } from '@/lib/trpc'

const { data, isLoading } = useQuery(productOptions.all({ limit: 12 }))
</script>

// apps/mobile/src/screens/(tabs)/_index.tsx
import { useQuery } from '@tanstack/react-query'
import { Image, View } from 'react-native'

import { Text } from '@/components/ui/text'
import { trpc } from '@/lib/trpc'

export default function IndexScreen() {
  return (
    <View className='flex-1 bg-background'>
      <View className='container flex-1 py-4'>
        <View className='flex-1 grid grid-cols-2 gap-4'>
          <ProductsList />
        </View>
      </View>
    </View>
  )
}

const ProductsList: React.FC = () => {
  const { data, isLoading } = useQuery(
    trpc.product.all.queryOptions({
      search: '',
      vendorId: null,
      categoryId: null,
      orderBy: 'createdAt_desc',
      limit: 6,
    }),
  )

  if (isLoading) return <Text>Loading...</Text>

  return data?.products.map((product) => (
    <View
      key={product.id}
      className='w-1/2 bg-card border border-border rounded-xl'
    >
      <Image
        source={{ uri: product.image ?? '' }}
        className='w-full aspect-square rounded-t-xl object-cover'
      />
      <View className='p-4'>
        <Text>{product.name}</Text>
      </View>
    </View>
  ))
}
